version: '2'

# https://hub.docker.com/r/bitnami/mongodb

services:
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=jira_data
