server:
  port: 8088

spring:
  main:
    banner-mode: "off"
  profiles:
    active: main

logging:
  level:
    root: WARN
    log4j: OFF
    org.slf4j: OFF
    ch.qos.logback: OFF
    com.dxfeed: ${LOGLEVEL:TRACE}

camel:
  component:
    mongodb:
      enabled: true

mongodb:
  host: localhost
  port: 27017
  user: ${MONGODB_USER:mongo}
  pass: ${MONGODB_PASSWORD:pass}
  db  : jira_data
